# Nombre de la aplicación
spring.application.name=futstars-backend

# Puerto
server.port=8080


# PostgreSQL (cuando conectemos Supabase)
# spring.datasource.url=
# spring.datasource.username=
# spring.datasource.password=


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Swagger
springdoc.swagger-ui.path=/swagger-ui.html